import { type Metadata } from "next";
import { ClerkProvider } from "@clerk/nextjs";
import { ThemeProvider } from "../components/ThemeProvider";
import { Providers } from "./providers";
import { Toaster } from "@/components/ui/sonner";
import "./globals.css";

export const metadata: Metadata = {
  title: "Clerk Next.js Quickstart",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider
      appearance={{
        layout: {
          socialButtonsPlacement: "bottom",
          socialButtonsVariant: "iconButton",
          unsafe_disableDevelopmentModeWarnings: true,
        },
      }}
    >
        <html lang="en" suppressHydrationWarning>
          <body className="antialiased bg-background text-foreground">
            <ThemeProvider
              attribute="class"
              defaultTheme="system"
              enableSystem
              disableTransitionOnChange
            >
              <Providers>
                <main>
                {children}
                </main>
                <Toaster />
              </Providers>
            </ThemeProvider>
          </body>
        </html>
    </ClerkProvider>
  );
}
